import { Equipment, Laborer } from "./types";

export const DEFAULT_EQUIPMENT: Equipment[] = [
  {
    id: "eq-1",
    name: "John Deere 5050 D Tractor",
    category: "agriculture",
    subCategory: "Tractor",
    image: "https://images.unsplash.com/photo-1594142404563-64ccc954aa79?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 1900,
    rating: 4.6,
    reviewsCount: 32,
    distance: 2.3,
    ownerName: "Ravi Kumar",
    ownerId: "owner-1",
    specs: {
      power: "50 HP",
      fuel: "Diesel",
      drive: "4 WD",
      year: "2019",
      operatorIncluded: true,
    },
    about: "Good condition tractor. Suitable for ploughing, transportation, and other farm works. Comes with an experienced operator if needed.",
    location: "Thirumanancheri, Tamil Nadu",
    verified: true,
    status: "active",
    usageHours: 120,
    lastServiceHours: 100,
    serviceDueIntervalHours: 50,
    serviceDue: false,
    deliveryZones: [
      { id: "z1-eq1", name: "Thirumanancheri Core", radiusKm: 5, deliveryFee: 300, color: "rgba(16, 185, 129, 0.15)" },
      { id: "z2-eq1", name: "Outer Suburbs (Kurumanakudi/Kuthalam)", radiusKm: 15, deliveryFee: 750, color: "rgba(245, 158, 11, 0.15)" },
      { id: "z3-eq1", name: "Extended Rural (Vaitheeswaran Koil/Aduthurai)", radiusKm: 35, deliveryFee: 1600, color: "rgba(239, 68, 68, 0.12)" }
    ]
  },
  {
    id: "eq-2",
    name: "Mahindra 575 DI Tractor",
    category: "agriculture",
    subCategory: "Tractor",
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 1800,
    rating: 4.6,
    reviewsCount: 32,
    distance: 2.1,
    ownerName: "Senthil Balaji",
    ownerId: "owner-2",
    specs: {
      power: "45 HP",
      fuel: "Diesel",
      drive: "2 WD",
      year: "2020",
      operatorIncluded: false,
    },
    about: "Highly fuel efficient Mahindra tractor. Recommended for dry land cultivation and harrowing.",
    location: "Vaitheeswaran Koil, Thirumanancheri",
    verified: true,
    status: "active",
    usageHours: 245,
    lastServiceHours: 200,
    serviceDueIntervalHours: 50,
    serviceDue: false
  },
  {
    id: "eq-3",
    name: "JCB 3DX Backhoe Loader",
    category: "construction",
    subCategory: "Excavator",
    image: "https://images.unsplash.com/photo-1579684389782-64d84b5e901d?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 9500,
    rating: 4.7,
    reviewsCount: 28,
    distance: 3.4,
    ownerName: "Arun Vignesh",
    ownerId: "owner-3",
    specs: {
      power: "76 HP",
      fuel: "Diesel",
      drive: "4 WD",
      year: "2021",
      operatorIncluded: true,
    },
    about: "JCB 3DX backhoe loader. Excellent condition, regularly serviced. Perfect for excavation, grading, lifting, and digging trenches. Driver fee included.",
    location: "Mayiladuthurai, Tamil Nadu",
    verified: true,
    status: "active",
    usageHours: 490,
    lastServiceHours: 400,
    serviceDueIntervalHours: 100,
    serviceDue: false,
    deliveryZones: [
      { id: "z1-eq3", name: "Bypass Local Radius", radiusKm: 8, deliveryFee: 400, color: "rgba(16, 185, 129, 0.15)" },
      { id: "z2-eq3", name: "Thirumanancheri Ring", radiusKm: 20, deliveryFee: 900, color: "rgba(245, 158, 11, 0.15)" },
      { id: "z3-eq3", name: "Vaitheeswaran Koil Core Belt", radiusKm: 40, deliveryFee: 1800, color: "rgba(239, 68, 68, 0.12)" }
    ]
  },
  {
    id: "eq-4",
    name: "Power Weeder 7.5 HP",
    category: "agriculture",
    subCategory: "Tillage",
    image: "https://images.unsplash.com/photo-1589923188900-85dae44fc3e3?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 1200,
    rating: 4.5,
    reviewsCount: 18,
    distance: 1.8,
    ownerName: "Murugan Swamy",
    ownerId: "owner-1",
    specs: {
      power: "7.5 HP",
      fuel: "Petrol",
      drive: "Manual",
      year: "2022",
      operatorIncluded: false,
    },
    about: "Compact power weeder, easy to navigate in narrow row spaces. Ideal for weeding in vegetable crops and fruit gardens.",
    location: "Kurumanakudi, Thirumanancheri",
    verified: true,
    status: "active",
    usageHours: 85,
    lastServiceHours: 50,
    serviceDueIntervalHours: 30,
    serviceDue: true
  },
  {
    id: "eq-5",
    name: "Power Tiller 12 HP",
    category: "agriculture",
    subCategory: "Tillage",
    image: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 1000,
    rating: 4.4,
    reviewsCount: 16,
    distance: 1.5,
    ownerName: "Gopalakrishnan",
    ownerId: "owner-4",
    specs: {
      power: "12 HP",
      fuel: "Diesel",
      drive: "2 WD",
      year: "2018",
      operatorIncluded: false,
    },
    about: "Heavy-duty power tiller for wet land puddling and crop residues incorporation. Very reliable.",
    location: "Kuthalam, Thirumanancheri",
    verified: true,
    status: "active",
    usageHours: 310,
    lastServiceHours: 300,
    serviceDueIntervalHours: 50,
    serviceDue: false
  },
  {
    id: "eq-6",
    name: "Paddy Transplanter 4 Row",
    category: "agriculture",
    subCategory: "Planting",
    image: "https://images.unsplash.com/photo-1563514223741-21b40e53a29b?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 3500,
    rating: 4.7,
    reviewsCount: 12,
    distance: 3.2,
    ownerName: "Ramachandran",
    ownerId: "owner-5",
    specs: {
      power: "5 HP",
      fuel: "Petrol",
      drive: "Walk-behind",
      year: "2020",
      operatorIncluded: true,
    },
    about: "Efficient 4-row walk-behind rice transplanter. Saves huge labor cost and ensures uniform planting.",
    location: "Aduthurai, Thirumanancheri",
    verified: true,
    status: "active",
    usageHours: 15,
    lastServiceHours: 0,
    serviceDueIntervalHours: 100,
    serviceDue: false
  },
  {
    id: "eq-7",
    name: "Harvester Kubota DC-70",
    category: "agriculture",
    subCategory: "Harvesting",
    image: "https://images.unsplash.com/photo-1595273670150-db0a3bf37bca?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 12000,
    rating: 4.8,
    reviewsCount: 8,
    distance: 4.6,
    ownerName: "Senthil Balaji",
    ownerId: "owner-2",
    specs: {
      power: "70 HP",
      fuel: "Diesel",
      drive: "Crawler Track",
      year: "2021",
      operatorIncluded: true,
    },
    about: "Kubota DC-70 combine harvester. Best-in-class performance in muddy fields. Minimal grain loss. Operators are highly skilled.",
    location: "Pandanallur, Thirumanancheri",
    verified: true,
    status: "active",
    usageHours: 620,
    lastServiceHours: 600,
    serviceDueIntervalHours: 100,
    serviceDue: false
  },
  {
    id: "eq-8",
    name: "Drone Sprayer 10L",
    category: "agriculture",
    subCategory: "Sprayer",
    image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 2500,
    rating: 4.5,
    reviewsCount: 20,
    distance: 2.8,
    ownerName: "Vikas Drone Services",
    ownerId: "owner-6",
    specs: {
      power: "Li-po Battery",
      fuel: "Electric",
      drive: "Hexacopter",
      year: "2023",
      operatorIncluded: true,
    },
    about: "10-liter payload agriculture drone spraying pesticide or fertilizer. Quick coverage of 1 acre in 10-15 minutes. Certified pilot included.",
    location: "Mayiladuthurai, Thirumanancheri",
    verified: true,
    status: "active"
  },
  {
    id: "eq-9",
    name: "Concrete Mixer Machine",
    category: "construction",
    subCategory: "Concrete mixer",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 2200,
    rating: 4.4,
    reviewsCount: 15,
    distance: 3.1,
    ownerName: "Ranganathan Builders",
    ownerId: "owner-7",
    specs: {
      power: "10 HP",
      fuel: "Diesel",
      drive: "Towable",
      year: "2021",
      operatorIncluded: false,
    },
    about: "Diesel concrete mixer machine with 1 bag capacity. Easy to move, highly sturdy frame. Great for house construction.",
    location: "Sembanarkoil, Thirumanancheri",
    verified: true,
    status: "active"
  },
  {
    id: "eq-10",
    name: "Heavy Silent Generator 62.5 kVA",
    category: "construction",
    subCategory: "Generator",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 5000,
    rating: 4.8,
    reviewsCount: 22,
    distance: 4.0,
    ownerName: "PowerMax Rentals",
    ownerId: "owner-8",
    specs: {
      power: "62.5 kVA",
      fuel: "Diesel",
      drive: "Stationary",
      year: "2022",
      operatorIncluded: true,
    },
    about: "Silent canopy diesel generator for uninterrupted power. Ideal for construction sites, marriages, and large events. Safe and low noise.",
    location: "Aduthurai, Thirumanancheri",
    verified: true,
    status: "active"
  },
  {
    id: "eq-11",
    name: "Premium Wedding Tent (Shamiana)",
    category: "function",
    subCategory: "Shamiana/Tent",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 8000,
    rating: 4.7,
    reviewsCount: 14,
    distance: 1.2,
    ownerName: "Sivam Decorators",
    ownerId: "owner-9",
    specs: {
      size: "40x60 ft",
      capacity: "250 Chairs",
      year: "2023",
    },
    about: "Elegant water-proof shamiana tent, beautifully decorated with red & white draping. Perfect for reception and outdoor parties.",
    location: "Thirumanancheri Temple, Tamil Nadu",
    verified: true,
    status: "active"
  },
  {
    id: "eq-12",
    name: "Demolition Rotary Hammer Drill",
    category: "tools",
    subCategory: "Drill machine",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 450,
    rating: 4.5,
    reviewsCount: 40,
    distance: 0.9,
    ownerName: "Sri Vigneshwara Tools",
    ownerId: "owner-10",
    specs: {
      power: "1500W",
      fuel: "Electric",
      weight: "6 kg",
    },
    about: "Professional high impact rotary hammer drill for concrete breaking and drilling. Multiple bits provided.",
    location: "Thiruvidaimarudur, Thirumanancheri",
    verified: true,
    status: "active"
  },
  {
    id: "eq-13",
    name: "New Power Tiller 15 HP",
    category: "agriculture",
    subCategory: "Power tiller",
    image: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80",
    pricePerDay: 1300,
    rating: 5.0,
    reviewsCount: 0,
    distance: 1.2,
    ownerName: "Murugan Swamy",
    ownerId: "owner-11",
    specs: {
      power: "15 HP",
      fuel: "Diesel",
      drive: "2 WD",
      year: "2024",
      operatorIncluded: false,
    },
    about: "Brand new high power tiller. Excellent for narrow fields.",
    location: "Kurumanakudi, Thirumanancheri",
    verified: false,
    status: "active"
  }
];

export const DEFAULT_LABORERS: Laborer[] = [
  {
    id: "lb-1",
    name: "Muthuvel K.",
    category: "Farm labor",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    pricePerDay: 600,
    rating: 4.5,
    reviewsCount: 45,
    location: "Kurumanakudi, Thirumanancheri",
    distance: 2.1,
    availability: "available",
    experience: "8 Years",
    verified: true,
    gender: "Male"
  },
  {
    id: "lb-2",
    name: "Karthik Raja",
    category: "Mason",
    image: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&w=150&q=80",
    pricePerDay: 900,
    rating: 4.7,
    reviewsCount: 32,
    location: "Kuthalam, Thirumanancheri",
    distance: 1.5,
    availability: "available",
    experience: "12 Years",
    verified: true,
    gender: "Male"
  },
  {
    id: "lb-3",
    name: "Palanisamy R.",
    category: "Carpenter",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    pricePerDay: 1000,
    rating: 4.6,
    reviewsCount: 28,
    location: "Thiruvidaimarudur, Thirumanancheri",
    distance: 3.2,
    availability: "available",
    experience: "10 Years",
    verified: true,
    gender: "Male"
  },
  {
    id: "lb-4",
    name: "Raju Krishnan",
    category: "Electrician",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80",
    pricePerDay: 1200,
    rating: 4.8,
    reviewsCount: 15,
    location: "Sembanarkoil, Thirumanancheri",
    distance: 2.5,
    availability: "available",
    experience: "6 Years",
    verified: true,
    gender: "Male"
  },
  {
    id: "lb-5",
    name: "Murugan Swamy",
    category: "Farm labor",
    image: "https://images.unsplash.com/photo-1541822557762-276686e08836?auto=format&fit=crop&w=150&q=80",
    pricePerDay: 700,
    rating: 5.0,
    reviewsCount: 0,
    location: "Kurumanakudi, Thirumanancheri",
    distance: 1.2,
    availability: "available",
    experience: "5 Years",
    verified: false,
    gender: "Male",
    kycDocName: "Aadhaar Card",
    kycStatus: "pending"
  },
  {
    id: "lb-6",
    name: "Karthikeyan P.",
    category: "Carpenter",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    pricePerDay: 1050,
    rating: 5.0,
    reviewsCount: 0,
    location: "Kuthalam, Thirumanancheri",
    distance: 1.8,
    availability: "available",
    experience: "8 Years",
    verified: false,
    gender: "Male",
    kycDocName: "GST Registration",
    kycStatus: "pending"
  }
];

export const CATEGORIES_METADATA = {
  agriculture: {
    title: "Agriculture Equipment",
    subCategories: ["Tractor", "Rotavator", "Power tiller", "Paddy transplanter", "Harvester", "Seed drill", "Sprayer", "Water pump", "Drone spraying", "Excavator (JCB)", "Mini tractor"]
  },
  construction: {
    title: "Construction Equipment",
    subCategories: ["Concrete mixer", "Vibrator", "Earth rammer", "Cutting machine", "Scaffolding", "Generator", "Welding machine", "Compressor", "Excavator", "Road roller"]
  },
  tools: {
    title: "General Tools",
    subCategories: ["Drill machine", "Pressure washer", "Chainsaw", "Lawn mower", "Ladder", "Tile cutter", "Power saw", "Grinder"]
  },
  function: {
    title: "Function & Event Materials",
    subCategories: ["Chairs", "Tables", "Shamiana/Tent", "Stage", "Lighting", "Sound system", "Projector", "LED wall", "Decorations", "Portable toilets"]
  },
  labor: {
    title: "Labor Services",
    subCategories: ["General", "Farm labor", "Mason", "Carpenter", "Electrician", "Plumber", "Painter", "Welder", "Driver", "Crane operator", "Event helpers", "House shifting labor"]
  }
};
