export const TRANSLATIONS = {
  en: {
    // Top branding bar / General
    app_title: "OorSevai",
    app_subtitle: "All Village Services in One App.",
    demo_profile: "Profile",
    my_bookings: "My Bookings",
    mvp: "⭐ MVP",
    role_customer: "Customer",
    role_owner: "Owner",
    role_labor: "Worker",
    role_admin: "Admin",
    role_label: "Role:",
    
    // Settings
    settings_title: "OorSevai Settings",
    language_switcher: "Application Language",
    lang_en: "English (ஆங்கிலம்)",
    lang_ta: "Tamil (தமிழ்)",
    settings_appearance: "Application Appearance",
    theme_light: "Light Theme",
    theme_dark: "Dark Theme",
    apply_close: "Apply & Close Settings",
    pwa_status: "App Health & Service Status",
    network_engine: "Network Engine",
    online_status: "Online (Fully Connected)",
    offline_status: "Offline Mode (Local Cache)",
    sw_code: "Service Worker Code",
    sw_running: "Registered & Running",
    cache_storage: "Local Cache Storage",
    cache_ver: "App Shell v1.4 (Cached offline)",
    
    // Tab bar Footer
    tab_home: "Home",
    tab_bookings: "Bookings",
    tab_ai_advisor: "AI Advisor",
    tab_provider: "Provider",
    tab_rent_mode: "Rent",
    tab_dashboard: "My Dashboard",
    tab_support: "Support",
    
    // Home View
    hello_user: "Hello, Udaya 👋",
    radius: "radius",
    rent_anything: "Rent Anything.",
    get_work_done: "Get Work Done.",
    tagline: "Connecting owners, local workers, and renters hyperlocally.",
    search_placeholder: "Search for tractors, workers, rotavators...",
    explore_cat: "Explore Service Categories",
    agriculture: "Agriculture",
    construction: "Construction",
    tools: "Tools &",
    machines: "Machines",
    function: "Function",
    materials: "Materials",
    labor: "Labor",
    services: "Services",
    
    // Quick categories and labels
    all_items: "All Items",
    general_tools: "General Tools",
    events_function: "Events & Function",
    labor_services: "Labor Services",
    
    // Weather
    weather_forecast: "Agricultural Weather Forecast",
    soil_temp: "Soil Temp",
    soil_moisture: "Soil Moisture",
    irrigation_advice: "Irrigation Advice",
    forecast_loading: "Fetching hyperlocal crop weather...",
    forecast_error: "Unable to retrieve weather forecast.",
    temp: "Temp",
    precip: "Precip",
    
    // Browse View
    operating_in: "Operating in",
    within: "within",
    filters: "Quick Filters",
    sort_by: "Sort By",
    distance: "Distance",
    price_low: "Price: Low to High",
    price_high: "Price: High to Low",
    rating: "Rating",
    verified_only: "Verified Only",
    available_today: "Available Today",
    lowest_price: "Lowest Price First",
    min_rating: "Min Rating",
    reset_filters: "Clear All",
    no_results: "No local equipment or workers found in this geofence radius.",
    try_adjust: "Try increasing search radius in Admin panel or changing filters.",
    
    // Actions & Buttons
    book_now: "Book Now",
    request_quote: "Request Quote",
    view_details: "View Details",
    call_now: "Call Now",
    chat_now: "Chat Now",
    back: "Back",
    verified: "Verified",
    not_verified: "Unverified",
    day: "day",
    hr: "hr",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    
    // Booking modal / Detail view
    book_header: "Confirm Booking Details",
    delivery_opt: "Delivery & Transit Options",
    pickup_self: "Self Pickup (Free)",
    delivery_home: "Provide Doorstep Delivery",
    booking_dates: "Booking Dates",
    start_date: "Start Date",
    end_date: "End Date",
    subtotal: "Subtotal",
    delivery_charge: "Delivery & Transit",
    platform_fee: "Platform Fee (10% Security)",
    grand_total: "Grand Total",
    booking_success: "Booking Created Successfully!",
    
    // Provider Dashboard
    provider_dashboard: "Service Provider Dashboard",
    total_earnings: "Total Earnings (after 10% platform fee)",
    active_rentals: "Active Rentals",
    upcoming_bookings: "Upcoming Bookings",
    add_new: "Add New Equipment",
    list_service: "List an Equipment / Machine",
    equipment_name: "Equipment Name",
    daily_rate: "Daily Rental Rate (₹)",
    hourly_rate: "Hourly Rental Rate (₹)",
    deposit: "Security Deposit Required (₹)",
    location: "Location Village",
    description: "Description & Condition",
    upload_photo: "Upload Photo",
    save_listing: "List Equipment",
    my_equipment: "My Listed Equipment & Rates",
    no_listings: "You haven't listed any equipment yet.",
    
    // Worker Dashboard
    worker_dashboard: "Labor & Worker Dashboard",
    work_status: "Work Availability Status",
    available: "Available for Hire",
    busy: "Busy / Unavailable",
    rate_per_day: "Expected Rate (₹/day)",
    skills_ex: "Specializations (comma separated)",
    update_profile: "Update Availability & Rate",
    labor_registered_desc: "Your laborer profile is listed hyperlocally for homeowners and farmers.",
    kyc_status: "KYC verification level:",
    unverified: "Unverified Draft",
    pending_kyc: "Pending Review",
    verified_kyc: "Government ID Verified ✅",
    jobs_queue: "Open Nearby Jobs & Work Inquiries",
    no_jobs: "No pending job inquiries at the moment.",
    
    // Admin Dashboard
    admin_title: "OorSevai Admin Control Desk",
    metrics: "System Health Metrics",
    total_bookings: "Total Bookings",
    total_revenue: "Total Platform Revenue",
    disputes: "Open Disputes",
    geofencing_control: "Service Coverage & Geofencing",
    operational_control: "Operational Control",
    center_location: "Center Location (Where service is set)",
    service_radius: "Service Radius (Surrounding Distance)",
    scope_summary: "Surrounding App Scope summary",
    scope_desc: "All products & laborer services outside this boundary are automatically geofenced (hidden) from the customer homepage.",
    save_geofence: "Save & Apply Geofence",
    kyc_queue: "KYC Verifications Queue",
    no_kyc: "No pending verification documents in queue.",
    disputes_desk: "Disputes & Escrow Protection Desk",
    no_disputes: "Zero open disputes. All payments and equipment returned smoothly.",
    
    // Chat Advisor
    advisor_welcome: "Vanakkam! I am your OorSevai AI agricultural advisor.",
    advisor_help: "Ask me anything about local crop farming, soil health, crop rotation, government subsidies, or how to lease tractors and hire workers on this app.",
    ask_question: "Ask OorSevai AI...",
    send: "Send",
    generating: "Thinking...",
    
    // Notifications
    alert_center: "Alert Center",
    clear_all: "Clear All",
    mark_all_read: "Mark all as read",
    no_notifications: "No alerts at the moment.",

    // Coverage extension
    price_low_high: "Price: Low to High",
    price_high_low: "Price: High to Low",
    top_rated: "Top Rated",
    no_listings_found: "No listings match your search",
    adjust_filters: "Try adjusting your subcategory filter or search keywords to find providers near you.",
    browse_categories: "Browse Categories",
    categories_count: "Categories",
    verified_owners: "Verified Owners",
    quality_assured: "Quality Assured",
    best_prices: "Best Prices",
    secure_escrow: "Secure Escrow",
    local_farming_weather: "Local Farming Weather",
    locating: "Locating...",
    use_my_location: "Use My Location",
    retrieving_forecast: "Retrieving farming forecast...",
    today: "Today",
    no_rain: "No Rain",
    farming_guidance: "Farming Guidance",
    advice: "Advice",
    live_open_meteo: "Live Open-Meteo API",
    smart_sowing_advice: "Smart Sowing & Protection Advice",
    popular_near_you: "Popular Near You",
    see_all: "See All",
    search_in: "Search in",
    and_above: "& above",
    all_ratings: "All Ratings",
    found: "Found",
    operating_in_geofence: "Operating in",
    within_radius: "within",
    geofence_active: "Geofence Active",
    quick_filters: "Quick Filters",
    lowest_price_first: "Lowest Price First",
    filter_by_rating: "Filter by Rating (Trusted Partners)",
    clear_filter: "Clear Filter",
    nearby: "Nearby",
    
    // Registration Form
    reg_title: "Create Your Profile",
    reg_subtitle: "Register once to access equipment renting, service provider, or work opportunities in your village.",
    reg_name_label: "Your Full Name",
    reg_name_placeholder: "e.g. Ram Kumar",
    reg_mobile_label: "Your Mobile Number",
    reg_mobile_placeholder: "e.g. 9876543210 (10 digits)",
    reg_roles_label: "What would you like to do? (Select all that apply)",
    reg_roles_desc: "Choose at least one role to continue. You can change these anytime in Settings.",
    reg_role_customer_title: "Customer / Renter",
    reg_role_customer_desc: "Rent agricultural tractors, tools, or hire local farm labor",
    reg_role_owner_title: "Equipment Owner",
    reg_role_owner_desc: "List your tractor, rotavator, or tools to earn extra income",
    reg_role_labor_title: "Worker / Laborer",
    reg_role_labor_desc: "Offer farm labor, masonry, carpentry, plumbing or electrician work",
    reg_admin_title: "Are you the Village Admin?",
    reg_admin_desc: "Enter the secure village admin passcode to unlock verification and dispute controls.",
    reg_admin_placeholder: "Passcode (e.g. 1234)",
    reg_admin_success: "✅ Admin access verified!",
    reg_admin_error: "❌ Invalid admin passcode",
    reg_btn_submit: "Complete Registration",
    reg_error_name: "Please enter your name",
    reg_error_mobile: "Please enter a valid 10-digit mobile number",
    reg_error_roles: "Please select at least one role",
    reg_location_label: "Your Location (City/Village)",
    reg_location_placeholder: "e.g. Thirumanancheri, Tamil Nadu",
    reg_location_detect: "Detect Location",
    reg_error_location: "Please specify or detect your location",
    settings_roles_title: "Registered Roles",
    settings_roles_desc: "Tick the roles you want to enable on your device",
    settings_profile_info: "Profile Information",
  },
  ta: {
    // Top branding bar / General
    app_title: "ஊர்சேவை",
    app_subtitle: "அனைத்து கிராம சேவைகளும் ஒரே செயலியில்.",
    demo_profile: "சுயவிவரம்",
    my_bookings: "எனது பதிவுகள்",
    mvp: "⭐ MVP",
    role_customer: "வாடிக்கையாளர்",
    role_owner: "உரிமையாளர்",
    role_labor: "தொழிலாளி",
    role_admin: "நிர்வாகி",
    role_label: "பங்கு:",
    
    // Settings
    settings_title: "ஊர்சேவை அமைப்புகள்",
    language_switcher: "செயலி மொழி",
    lang_en: "English (ஆங்கிலம்)",
    lang_ta: "Tamil (தமிழ்)",
    settings_appearance: "செயலி தோற்றம்",
    theme_light: "ஒளி தோற்றம் (Light)",
    theme_dark: "இருள் தோற்றம் (Dark)",
    apply_close: "அமைப்புகளைப் பயன்படுத்து & மூடு",
    pwa_status: "செயலி நிலை & சேவை நிலை",
    network_engine: "நெட்வொர்க் என்ஜின்",
    online_status: "ஆன்லைன் (முழுமையாக இணைக்கப்பட்டுள்ளது)",
    offline_status: "ஆஃப்லைன் முறை (உள்ளூர் தற்காலிக சேமிப்பு)",
    sw_code: "சர்வீஸ் வொர்க்கர் குறியீடு",
    sw_running: "பதிவு செய்யப்பட்டு இயங்குகிறது",
    cache_storage: "உள்ளூர் தற்காலிக சேமிப்பு",
    cache_ver: "ஆப் ஷெல் v1.4 (ஆஃப்லைனில் சேமிக்கப்பட்டது)",
    
    // Tab bar Footer
    tab_home: "முகப்பு",
    tab_bookings: "பதிவுகள்",
    tab_ai_advisor: "AI ஆலோசகர்",
    tab_provider: "வழங்குநர்",
    tab_rent_mode: "வாடகை",
    tab_dashboard: "என் கட்டுப்பாட்டு பலகை",
    tab_support: "ஆதரவு",
    
    // Home View
    hello_user: "வணக்கம், உதயா 👋",
    radius: "வட்டம்",
    rent_anything: "உங்கள் தேவை,",
    get_work_done: "எங்கள் சேவை!",
    tagline: "உங்கள் பகுதியில் உள்ள உரிமையாளர்கள், தொழிலாளர்கள் மற்றும் வாடகையாளர்களை ஒன்றிணைக்கும் தளம்.",
    search_placeholder: "டிராக்டர், தொழிலாளர்கள், ரோட்டாவேட்டர்களைத் தேடுங்கள்...",
    explore_cat: "சேவை பிரிவுகளை ஆராயுங்கள்",
    agriculture: "விவசாயம்",
    construction: "கட்டுமானம்",
    tools: "கருவிகள் &",
    machines: "இயந்திரங்கள்",
    function: "விழா",
    materials: "பொருட்கள்",
    labor: "தொழிலாளர்கள்",
    services: "சேவைகள்",
    
    // Quick categories and labels
    all_items: "அனைத்து பொருட்கள்",
    general_tools: "பொதுவான கருவிகள்",
    events_function: "விழாக்கள் & நிகழ்ச்சிகள்",
    labor_services: "தொழிலாளர் சேவைகள்",
    
    // Weather
    weather_forecast: "விவசாய வானிலை அறிக்கை",
    soil_temp: "மண் வெப்ப நிலை",
    soil_moisture: "மண் ஈரப்பதம்",
    irrigation_advice: "நீர்ப்பாசன ஆலோசனை",
    forecast_loading: "வானிலை அறிக்கை பெறப்படுகிறது...",
    forecast_error: "வானிலை அறிக்கையைப் பெற முடியவில்லை.",
    temp: "வெப்பநிலை",
    precip: "மழைப்பொழிவு",
    
    // Browse View
    operating_in: "இயங்கும் இடம்",
    within: "சுற்றளவு",
    filters: "விரைவு வடிகட்டிகள்",
    sort_by: "வரிசைப்படுத்து",
    distance: "தொலைவு",
    price_low: "விலை: குறைந்ததிலிருந்து அதிகம்",
    price_high: "விலை: அதிகத்திலிருந்து குறைவு",
    rating: "மதிப்பீடு",
    verified_only: "சரிபார்க்கப்பட்டவை மட்டும்",
    available_today: "இன்று கிடைப்பவை",
    lowest_price: "குறைந்த விலை முதலில்",
    min_rating: "குறைந்தபட்ச மதிப்பீடு",
    reset_filters: "அனைத்தையும் நீக்கு",
    no_results: "இந்த சுற்றளவில் உள்ளூர் உபகரணங்களோ தொழிலாளர்களோ கிடைக்கவில்லை.",
    try_adjust: "நிர்வாகி பேனலில் தேடல் சுற்றளவை அதிகரிக்கவும் அல்லது வடிகட்டிகளை மாற்றவும்.",
    
    // Actions & Buttons
    book_now: "இப்போதே பதிவு செய்",
    request_quote: "மதிப்பீடு கேள்",
    view_details: "விவரங்களை காண்க",
    call_now: "அழைக்கவும்",
    chat_now: "அரட்டை செய்",
    back: "பின்னால்",
    verified: "சரிபார்க்கப்பட்டது",
    not_verified: "சரிபார்க்கப்படாதது",
    day: "நாள்",
    hr: "மணிநேரம்",
    cancel: "ரத்து செய்",
    confirm: "உறுதி செய்",
    save: "சேமி",
    
    // Booking modal / Detail view
    book_header: "பதிவு விவரங்களை உறுதிப்படுத்தவும்",
    delivery_opt: "டெலிவரி & போக்குவரத்து விருப்பங்கள்",
    pickup_self: "சுயமாக எடுத்துச் செல்லுதல் (இலவசம்)",
    delivery_home: "வீட்டு வாசலில் டெலிவரி செய்தல்",
    booking_dates: "பதிவு தேதிகள்",
    start_date: "தொடக்க தேதி",
    end_date: "முடிவு தேதி",
    subtotal: "துணைத்தொகை",
    delivery_charge: "டெலிவரி & போக்குவரத்து",
    platform_fee: "தள கட்டணம் (10% பாதுகாப்பு)",
    grand_total: "மொத்த தொகை",
    booking_success: "பதிவு வெற்றிகரமாக உருவாக்கப்பட்டது!",
    
    // Provider Dashboard
    provider_dashboard: "சேவை வழங்குநர் கட்டுப்பாட்டு பலகை",
    total_earnings: "மொத்த வருவாய் (10% தளக் கட்டணத்திற்குப் பிறகு)",
    active_rentals: "செயலில் உள்ள வாடகைகள்",
    upcoming_bookings: "வரவிருக்கும் பதிவுகள்",
    add_new: "புதிய உபகரணத்தைச் சேர்",
    list_service: "ஒரு உபகரணம் / இயந்திரத்தை பட்டியலிடுங்கள்",
    equipment_name: "உபகரணத்தின் பெயர்",
    daily_rate: "தினசரி வாடகை வீதம் (₹)",
    hourly_rate: "மணிநேர வாடகை வீதம் (₹)",
    deposit: "தேவைப்படும் பாதுகாப்பு வைப்புத்தொகை (₹)",
    location: "அமைந்துள்ள கிராமம்",
    description: "விளக்கம் & தற்போதைய நிலை",
    upload_photo: "புகைப்படத்தைப் பதிவேற்றவும்",
    save_listing: "உபகரணத்தை பட்டியலிடு",
    my_equipment: "என் பட்டியலிடப்பட்ட உபகரணங்கள் & கட்டணங்கள்",
    no_listings: "நீங்கள் இன்னும் எந்த உபகரணத்தையும் பட்டியலிடவில்லை.",
    
    // Worker Dashboard
    worker_dashboard: "தொழிலாளர்கள் கட்டுப்பாட்டு பலகை",
    work_status: "வேலை கிடைக்கும் நிலை",
    available: "வேலைக்குக் கிடைக்கிறார்",
    busy: "வேலையில் உள்ளார் / கிடைக்கவில்லை",
    rate_per_day: "எதிர்பார்க்கும் தினசரி சம்பளம் (₹/நாள்)",
    skills_ex: "சிறப்புத் திறன்கள் (காற்புள்ளியால் பிரிக்கவும்)",
    update_profile: "கிடைக்கும் நிலை & சம்பளத்தை புதுப்பி",
    labor_registered_desc: "உங்கள் தொழிலாளி விவரங்கள் உள்ளூர் விவசாயிகள் மற்றும் வீட்டு உரிமையாளர்களுக்குக் காண்பிக்கப்படுகிறது.",
    kyc_status: "KYC சரிபார்ப்பு நிலை:",
    unverified: "சரிபார்க்கப்படாத வரைவு",
    pending_kyc: "சரிபார்ப்பில் உள்ளது",
    verified_kyc: "அரசு ஐடி சரிபார்க்கப்பட்டது ✅",
    jobs_queue: "அருகிலுள்ள வேலைகள் & விசாரணைகள்",
    no_jobs: "தற்போது நிலுவையில் உள்ள வேலை விசாரணைகள் எதுவும் இல்லை.",
    
    // Admin Dashboard
    admin_title: "ஊர்சேவை நிர்வாகக் கட்டுப்பாட்டு மேசை",
    metrics: "அமைப்பின் முக்கிய அளவீடுகள்",
    total_bookings: "மொத்த பதிவுகள்",
    total_revenue: "தளத்தின் மொத்த வருவாய்",
    disputes: "அனைத்து சர்ச்சைகள்",
    geofencing_control: "சேவை எல்லை & புவிசார் கட்டுப்பாடு",
    operational_control: "செயல்பாட்டு கட்டுப்பாடு",
    center_location: "மைய இருப்பிடம் (சேவை அமைக்கப்பட்டுள்ள இடம்)",
    service_radius: "சேவை ஆரம் (சுற்றியுள்ள தூரம்)",
    scope_summary: "சுற்றியுள்ள செயலியின் எல்லைச் சுருக்கம்",
    scope_desc: "இந்த எல்லைக்கு வெளியேயுள்ள அனைத்து தயாரிப்புகளும் தொழிலாளர் சேவைகளும் வாடிக்கையாளர் முகப்புப் பக்கத்திலிருந்து தானாகவே மறைக்கப்படும்.",
    save_geofence: "புவிசார் எல்லையை சேமி & பயன்படுத்து",
    kyc_queue: "KYC சரிபார்ப்பு வரிசை",
    no_kyc: "சரிபார்ப்பு வரிசையில் ஆவணங்கள் எதுவும் இல்லை.",
    disputes_desk: "சர்ச்சைகள் & எஸ்க்ரோ பாதுகாப்பு மேசை",
    no_disputes: "சர்ச்சைகள் ஏதுமில்லை. அனைத்து கொடுப்பனவுகளும் உபகரணங்களும் சுமுகமாகத் திரும்பப் பெறப்பட்டன.",
    
    // Chat Advisor
    advisor_welcome: "வணக்கம்! நான் உங்கள் ஊர்சேவை AI விவசாய ஆலோசகர்.",
    advisor_help: "உள்ளூர் பயிர் விவசாயம், மண் வளம், பயிர் சுழற்சி, அரசு மானியங்கள் அல்லது இந்த செயலியில் டிராக்டர்களை வாடகைக்கு எடுப்பது மற்றும் தொழிலாளர்களை வேலைக்கு அமர்த்துவது பற்றி என்னிடம் கேளுங்கள்.",
    ask_question: "ஊர்சேவை AI-இடம் கேளுங்கள்...",
    send: "அனுப்பு",
    generating: "யோசிக்கிறது...",
    
    // Notifications
    alert_center: "அறிவிப்பு மையம்",
    clear_all: "அனைத்தையும் நீக்கு",
    mark_all_read: "அனைத்தையும் படித்ததாகக் குறி",
    no_notifications: "தற்போது அறிவிப்புகள் ஏதுமில்லை.",

    // Coverage extension
    price_low_high: "விலை: குறைந்ததிலிருந்து அதிகம்",
    price_high_low: "விலை: அதிகத்திலிருந்து குறைவு",
    top_rated: "சிறந்த மதிப்பீடு",
    no_listings_found: "உங்கள் தேடலுக்கு முடிவுகள் எதுவும் இல்லை",
    adjust_filters: "உங்களுக்கு அருகிலுள்ள வழங்குநர்களைக் கண்டறிய உங்கள் துணைப்பிரிவு வடிகட்டி அல்லது தேடல் சொற்களை மாற்றியமைக்கவும்.",
    browse_categories: "பிரிவுகளை ஆராயுங்கள்",
    categories_count: "பிரிவுகள்",
    verified_owners: "சரிபார்க்கப்பட்டது",
    quality_assured: "தரம் உறுதி",
    best_prices: "சிறந்த விலை",
    secure_escrow: "பணப் பாதுகாப்பு",
    local_farming_weather: "உள்ளூர் விவசாய வானிலை",
    locating: "இருப்பிடத்தைத் தேடுகிறது...",
    use_my_location: "என் இருப்பிடத்தைப் பயன்படுத்து",
    retrieving_forecast: "விவசாய வானிலை அறிக்கை பெறப்படுகிறது...",
    today: "இன்று",
    no_rain: "மழை இல்லை",
    farming_guidance: "விவசாய வழிகாட்டுதல்",
    advice: "ஆலோசனை",
    live_open_meteo: "நேரடி ஓபன்-மெட்டியோ API",
    smart_sowing_advice: "புத்திசாலித்தனமான விதைப்பு மற்றும் பாதுகாப்பு ஆலோசனைகள்",
    popular_near_you: "உங்களுக்கு அருகில் பிரபலமானவை",
    see_all: "அனைத்தையும் காண்க",
    search_in: "தேடுங்கள்",
    and_above: "& அதற்கு மேல்",
    all_ratings: "அனைத்து மதிப்பீடுகளும்",
    found: "கிடைத்துள்ளன",
    operating_in_geofence: "இயங்கும் இடம்",
    within_radius: "சுற்றளவு",
    geofence_active: "புவிசார் எல்லை செயலில் உள்ளது",
    quick_filters: "விரைவு வடிகட்டிகள்",
    lowest_price_first: "குறைந்த விலை முதலில்",
    filter_by_rating: "மதிப்பீட்டின்படி வடிகட்டவும்",
    clear_filter: "வடிகட்டியை நீக்கு",
    nearby: "அருகிலுள்ளவை",
    
    // Registration Form
    reg_title: "உங்கள் சுயவிவரத்தை உருவாக்கவும்",
    reg_subtitle: "உங்கள் கிராமத்தில் உபகரணங்கள் வாடகைக்கு எடுக்க, சேவை வழங்க அல்லது வேலை வாய்ப்புகளைப் பெற ஒருமுறை பதிவு செய்யவும்.",
    reg_name_label: "உங்கள் முழு பெயர்",
    reg_name_placeholder: "எ.கா. ராம் குமார்",
    reg_mobile_label: "உங்கள் அலைபேசி எண்",
    reg_mobile_placeholder: "எ.கா. 9876543210 (10 இலக்கங்கள்)",
    reg_roles_label: "நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்? (பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்)",
    reg_roles_desc: "தொடர குறைந்தது ஒரு பங்கையாவது தேர்ந்தெடுக்கவும். இதை அமைப்புகளில் எப்போது வேண்டுமானாலும் மாற்றலாம்.",
    reg_role_customer_title: "வாடிக்கையாளர் / வாடகைதாரர்",
    reg_role_customer_desc: "விவசாய டிராக்டர்கள், கருவிகள் வாடகைக்கு எடுக்க அல்லது தொழிலாளர்களை வேலைக்கு அமர்த்த",
    reg_role_owner_title: "உபகரண உரிமையாளர்",
    reg_role_owner_desc: "கூடுதல் வருமானம் ஈட்ட உங்கள் டிராக்டர், ரொட்டாவேட்டர் அல்லது கருவிகளைப் பட்டியலிடுங்கள்",
    reg_role_labor_title: "தொழிலாளி",
    reg_role_labor_desc: "விவசாய வேலை, கொத்தனார், தச்சர், பிளம்பர் அல்லது எலக்ட்ரீஷியன் வேலைகளை வழங்க",
    reg_admin_title: "நீங்கள் கிராம நிர்வாகியா?",
    reg_admin_desc: "சரிபார்ப்பு மற்றும் தகராறு கட்டுப்பாடுகளைத் திறக்க பாதுகாப்பான கிராம நிர்வாக கடவுக்குறியீட்டை உள்ளிடவும்.",
    reg_admin_placeholder: "கடவுக்குறியீடு (எ.கா. 1234)",
    reg_admin_success: "✅ நிர்வாகி அணுகல் சரிபார்க்கப்பட்டது!",
    reg_admin_error: "❌ தவறான கடவுக்குறியீடு",
    reg_btn_submit: "பதிவை நிறைவு செய்",
    reg_error_name: "தயவுசெய்து உங்கள் பெயரை உள்ளிடவும்",
    reg_error_mobile: "தயவுசெய்து சரியான 10 இலக்க அலைபேசி எண்ணை உள்ளிடவும்",
    reg_error_roles: "குறைந்தது ஒரு பங்கையாவது தேர்ந்தெடுக்கவும்",
    reg_location_label: "உங்கள் இருப்பிடம் (நகரம்/கிராமம்)",
    reg_location_placeholder: "எ.கா. கோயம்புத்தூர், தமிழ்நாடு",
    reg_location_detect: "இருப்பிடத்தைக் கண்டறி",
    reg_error_location: "தயவுசெய்து உங்கள் இருப்பிடத்தைக் குறிப்பிடவும் அல்லது கண்டறியவும்",
    settings_roles_title: "பதிவு செய்யப்பட்ட பங்குகள்",
    settings_roles_desc: "உங்கள் சாதனத்தில் நீங்கள் செயல்படுத்த விரும்பும் பங்குகளை டிக் செய்யவும்",
    settings_profile_info: "சுயவிவரத் தகவல்",
  }
};

export type Language = "en" | "ta";

export function getTranslation(lang: Language, key: keyof typeof TRANSLATIONS.en): string {
  const dictionary = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return dictionary[key] || TRANSLATIONS.en[key] || String(key);
}
